cabal-version:      3.0
name:               agentic-examples
version:            0.2.0.0
synopsis:           The examples from the haskell-agentic README
license:            MIT
build-type:         Simple

executable dino
  default-language: GHC2021
  default-extensions:
    DeriveAnyClass
    DerivingVia
    LambdaCase
    OverloadedStrings
  ghc-options:      -Wall
  hs-source-dirs:   .
  main-is:          Dino.hs
  build-depends:
    , agentic
    , agentic-anthropic
    , agentic-io
    , agentic-jev
    , base
    , text

executable review
  default-language: GHC2021
  default-extensions:
    DeriveAnyClass
    DerivingVia
    LambdaCase
    OverloadedStrings
  ghc-options:      -Wall
  hs-source-dirs:   .
  main-is:          Review.hs
  build-depends:
    , agentic
    , agentic-io
    , agentic-jev
    , base
    , text

executable tictactoe
  default-language: GHC2021
  default-extensions:
    DeriveAnyClass
    DerivingVia
    LambdaCase
    OverloadedStrings
  ghc-options:      -Wall
  hs-source-dirs:   .
  main-is:          TicTacToe.hs
  build-depends:
    , agentic
    , agentic-anthropic
    , agentic-io
    , base
    , text
